### ISSUE TITLE
Implement additional art assets for Act. 2 of dev fundamentals

### ISSUE THREAD

**Issue by rmkubik** [TwilioQuest/twilioquest-dev-fundamentals#22]
- Prepare a list of new assets we think could enhance the level.
- Prioritize these assets.
- Estimate how many we think we could deliver in this milestone vs. future ones.

**Comment by kerrlake** [comment]
General Visual Additions:

- [x] Side Stairs + Railings
- [x] Tv On/Off animations
- [x] Table
- [x] Chairs (4 directions)
- [x] Server blinking animation
- [ ] Book cart
- [ ] Computer (On/Booted up version)
- [ ] Side-facing book podium
- [ ] Record Player
- [ ] Old Radio

Cutlery/Drawer Specific Additions

- [ ] Giant Decorative Spoons
- [ ] Wall of drawers
- [ ] Cabinet of drawers

**Comment by rmkubik** [comment]
Sweet! If we want to commit to this list, let's update it from a "proposal" to a "feature" and then we can update the name too.

**Comment by kerrlake** [comment]
I'm not sure if I have access to change the labels! GitHub is telling me there should be a little gear "settings" button next to labels that I'm not seeing.

**Comment by rmkubik** [comment]
Oh, oops! Okay, I can figure out permissions later! I updated that and will change the title too. :-)
