### ISSUE TITLE
Update Librarian npc animations to wake up after first player interaction

### ISSUE THREAD

**Issue by kerrielake** [TwilioQuest/twilioquest-dev-fundamentals#30]
When the Operator first meets the Librarian npc, she is sleeping. Currently, she stays sleeping even after the player talks to her. It would be ideal if this sequence changed to:

1. "Sleeping idle" is playing (looping)
2. Player presses button to interact with Librarian
3. Animation changes to "waking up" animation (non-looping)
4. Animation changes to "awake idle" animation (looping)
5. Dialogue box then pops up
6. Librarian stays in "awake idle" animation after the first interaction from this point forward.

The Librarian is also sleeping on the other floors as well, these should also be changed to the awake animations.

**Comment by rmkubik** [comment]
@kerrielake would you be able to specific the frames that correspond to each animation you're describing?

These are the ones currently listed in the object configs:
https://github.com/TwilioQuest/twilioquest-base/blob/main/objects/librarian-npc/config.js#L5-L12
https://github.com/TwilioQuest/twilioquest-base/blob/main/objects/librarian-npc-monitor/config.js#L5-L8

If you write the info here I can update base to include the other animations, or you could open a PR with the added animations to twilioquest-base.

**Comment by kerrielake** [comment]
@rmkubik 

Seems like the current idle and sleeping animation frames are actually incorrect, the whole first row of the spritesheet should be the sleeping animation! 

Sleeping would be frames [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

Waking Up: [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]

Awake/Idle: [36, 37, 38, 39, 40, 41]

Shocked (not needed for this sequence): [54, 55, 56, 57, 58, 59, 60]

**Comment by rmkubik** [comment]
Shipped in 3.11.0!
